//CSD
char sql_CreateCSD[] = "CREATE TABLE IF NOT EXISTS mh_CSD (steamid VARCHAR(32) NOT NULL, enabled INT(12) NOT NULL DEFAULT '0', speedaxis INT(12) NOT NULL DEFAULT '0', pos VARCHAR(32) NOT NULL DEFAULT '0.5|0.5', gaincolor VARCHAR(32) NOT NULL DEFAULT '255|255|255', losscolor VARCHAR(32) NOT NULL DEFAULT '255|255|255', maintaincolor VARCHAR(32) NOT NULL DEFAULT '255|255|255', updaterate INT(12) NOT NULL DEFAULT '0', PRIMARY KEY(steamid)) DEFAULT CHARSET=utf8mb4;";

//KEYS
char sql_CreateKeys[] = "CREATE TABLE IF NOT EXISTS mh_KEYS (steamid VARCHAR(32) NOT NULL, enabled INT(12) NOT NULL DEFAULT '0', pos VARCHAR(32) NOT NULL DEFAULT '0.5|0.5', color VARCHAR(32) NOT NULL DEFAULT '255|255|255', updaterate INT(12) NOT NULL DEFAULT '0', PRIMARY KEY(steamid)) DEFAULT CHARSET=utf8mb4;";

//SYNC
char sql_CreateSync[] = "CREATE TABLE IF NOT EXISTS mh_SYNC (steamid VARCHAR(32) NOT NULL, enabled INT(12) NOT NULL DEFAULT '0', pos VARCHAR(32) NOT NULL DEFAULT '0.5|0.5', color VARCHAR(32) NOT NULL DEFAULT '255|255|255', updaterate INT(12) NOT NULL DEFAULT '0', PRIMARY KEY(steamid)) DEFAULT CHARSET=utf8mb4;";

//CHECKPOINTS
char sql_CreateCP[] = "CREATE TABLE IF NOT EXISTS mh_CP (steamid VARCHAR(32) NOT NULL, enabled INT(12) NOT NULL DEFAULT '0', pos VARCHAR(32) NOT NULL DEFAULT '0.5|0.5', gaincolor VARCHAR(32) NOT NULL DEFAULT '255|255|255', losscolor VARCHAR(32) NOT NULL DEFAULT '255|255|255', maintaincolor VARCHAR(32) NOT NULL DEFAULT '255|255|255', holdtime INT(12) NOT NULL DEFAULT '3', comparemode INT(12) NOT NULL DEFAULT '1', PRIMARY KEY(steamid)) DEFAULT CHARSET=utf8mb4;";

//CHECKPOINTS
char sql_CreateTimer[] = "CREATE TABLE IF NOT EXISTS mh_TIMER (steamid VARCHAR(32) NOT NULL, enabled INT(12) NOT NULL DEFAULT '0', pos VARCHAR(32) NOT NULL DEFAULT '0.5|0.5', normalcolor VARCHAR(32) NOT NULL DEFAULT '255|255|255', slowercolor VARCHAR(32) NOT NULL DEFAULT '255|255|255', comparemode INT(12) NOT NULL DEFAULT '1', PRIMARY KEY(steamid)) DEFAULT CHARSET=utf8mb4;";

//CHECKPOINTS
char sql_CreateMapInfo[] = "CREATE TABLE IF NOT EXISTS mh_MAPINFO (steamid VARCHAR(32) NOT NULL, enabled INT(12) NOT NULL DEFAULT '0', pos VARCHAR(32) NOT NULL DEFAULT '0.5|0.5', color VARCHAR(32) NOT NULL DEFAULT '255|255|255', showmode INT(12) NOT NULL DEFAULT '0', comparemode INT(12) NOT NULL DEFAULT '1', PRIMARY KEY(steamid)) DEFAULT CHARSET=utf8mb4;";
